language: php
matrix:
  include:
  - php: 7.1
  - php: 7.2
  - php: 7.3
  fast_finish: true
  allow_failures:
  - php: 7.3

install:
- composer install --prefer-dist --no-interaction --no-progress

script:
- vendor/bin/phpunit tests/MarkdownTest.php
